const CONFIG = {
    titleWeb: "batngochuabaza",
    introTitle: 'He luu cậu!',
    introDesc: `Tớ có điều này muốn nói với cậu ._.`,
    btnIntro: '^^OKe^^',
    title: 'Tớ có điều này muốn hỏi cậu phải trả lời thật lòng nha ._.',
    desc: 'Cậu có ny chưa nè, có bất ngờ phía sau nhé :> ',
    btnYes: 'Chưa có ny nựa :<',
    btnNo: 'Có rồi nha lêu lêu :>',
    question: 'Biết ngay là chưa có ny mà, thấy tớ đoán ghê chưa ?',
    btnReply: 'Gửi cậu nè <3',
    reply: 'Whyyy',
    mess: 'Thôi không có ny cũng không sao hết',
    messDesc: 'Nhân ngày phụ nữ Việt Nam ( tuy cậu chưa là phụ nữ), tớ chúc cậu ngày càng xênh đẹp, luôn cutee phô mai que, luôn vui vẻ, đạt đc nhiều thành công trên con đường đã chọn, và đặc biệt là sớm có ny nè :>',
    btnAccept: 'Cảm ơn cậu nhìuuuu <3',
